version: '3.8'

services:
  pandoc-latex:
    build:
      context: .
      dockerfile: pandoc-latex/Dockerfile
    ports:
      - "4000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  puppeteer-mcp:
    build:
      context: .
      dockerfile: puppeteer/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./puppeteer/linux-chrome-profile:/app/puppeteer/linux-chrome-profile
      - ./puppeteer/assets/:/app/puppeteer/assets
    environment:
      - NODE_ENV=production
    restart: unless-stopped