services:
  pandoc-latex:
    build:
      context: .
      dockerfile: pandoc-latex/Dockerfile
    ports:
      - "4000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  puppeteer-mcp:
    develop:
      watch:
      - action: sync+restart
        path: ./puppeteer/src/
        target: /app/puppeteer/src/
        ignore:
          - node_modules/
    build:
      context: .
      dockerfile: puppeteer/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./puppeteer/linux-chrome-profile:/app/puppeteer/linux-chrome-profile
      - ./puppeteer/assets:/app/puppeteer/assets
    environment:
      - NODE_ENV=production
    restart: unless-stopped