services:
  pandoc-latex:
    build:
      context: .
      dockerfile: ./packages/pandoc-latex/Dockerfile
    ports:
      - "4000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  puppeteer-mcp:
    develop:
      watch:
      - action: sync+restart
        path: ./packages/puppeteer/src/
        target: /app/packages/puppeteer/src/
        ignore:
          - node_modules/
    build:
      context: .
      dockerfile: packages/puppeteer/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./packages/puppeteer/linux-chrome-profile:/app/packages/puppeteer/linux-chrome-profile
      - ./packages/puppeteer/assets:/app/packages/puppeteer/assets
    environment:
      - NODE_ENV=production
    restart: unless-stopped